[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "dockerfile"
formatter = { command = "dprint", args = ["fmt", "--stdin", "dockerfile"] }

[[language]]
name = "toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }

[[language]]
name = "yaml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-bn"] }
