format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = " "
format = "[$symbol$virtualenv]($style) "
style = "yellow"
