theme = "catppuccin-mocha"
# theme = "auto"
mode = "auto"
watch = false
exclude_untracked = true
line_numbers = false
tab_width = 4
wrap_lines = false
hunk_headers = true
menu_bar = false
sidebar = false
agent_notes = true
transparent_background = true
copy_decorations = false
cursor_line = "number"

[vcs]
watch = true

[pager]
menu_bar = false
wrap_lines = true
